// generated by Fast Light User Interface Designer (fluid) version 1.0300

#ifndef test_h
#define test_h
#include <FL/Fl.H>
#include <FL/Fl_Double_Window.H>
#include "ffffltk.h"

class FancyUI {
public:
  Fl_Double_Window* make_window();
};
#endif
